name: pulsar-io-cloud-storage integration tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build
        run: mvn clean package -DskipTests

      - name: test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: error
          command: |
            ./.ci/integrations/start.sh
            mvn -Dtest=*IntegrationTest test -DfailIfNoTests=false
            ./.ci/integrations/stop.sh
